import { defineConfig } from 'astro/config';
// Sitemap is generated by scripts/generate-sitemap.mjs, which runs automatically
// via the "postbuild" npm script after every `npm run build`. No manual re-run needed.
// @astrojs/sitemap is intentionally disabled — the custom script handles 19K+ ZIP/state
// pages that the Astro integration cannot enumerate from SSG routes alone.
// import sitemap from '@astrojs/sitemap';

export default defineConfig({
  site: 'https://internet4all.com',
  output: 'static',
  integrations: [],
  vite: {
    css: {
      preprocessorOptions: {}
    }
  }
});
