import { defineConfig } from 'astro/config';
import { fileURLToPath } from 'url';
import path from 'path';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
// Sitemap is generated by scripts/generate-sitemap.mjs, which runs automatically
// via the "postbuild" npm script after every `npm run build`. No manual re-run needed.
// @astrojs/sitemap is intentionally disabled — the custom script handles 19K+ ZIP/state
// pages that the Astro integration cannot enumerate from SSG routes alone.
// import sitemap from '@astrojs/sitemap';

export default defineConfig({
  site: 'https://internet-4-all.com',
  output: 'static',
  prefetch: true,
  integrations: [],
  vite: {
    resolve: {
      alias: {
        '@': path.resolve(__dirname, 'src'),
        '@components': path.resolve(__dirname, 'src/components'),
        '@layouts': path.resolve(__dirname, 'src/layouts'),
        '@data': path.resolve(__dirname, 'src/data'),
        '@lib': path.resolve(__dirname, 'src/lib'),
        '@styles': path.resolve(__dirname, 'src/styles'),
      }
    },
    css: {
      preprocessorOptions: {}
    }
  }
});
