#!/usr/bin/env python3
"""Generate updated providers.json from March 2026 ISP research data."""
import json, os

data = {
  "providers": [
    {
      "id": "spectrum",
      "name": "Spectrum",
      "slug": "spectrum",
      "logo": "https://cdn.builder.io/api/v1/image/assets%2F3e261a0dd1144caf9d53950dd45223ca%2F7d5ab395a1f74bf7ada360ff15b5a626?format=webp&width=200",
      "types": ["cable", "fiber"],
      "rating": 4.2,
      "reviewCount": 45230,
      "isPartner": True,
      "description": "Spectrum offers no-contract, no-data-cap internet with plans starting at just $30/mo. Their 2026 lineup features WiFi 7 routers on Gig plans, a $500 contract buyout for switchers, and a free year of Spectrum Mobile on select tiers — making it one of the best values in cable internet.",
      "pros": ["No data caps on any plan", "No contracts required", "Free modem included", "WiFi 7 router on Gig plans", "$500 contract buyout for new customers", "Spectrum Mobile included (1 yr) on Gig+", "Wide nationwide availability", "30-day money-back guarantee"],
      "cons": ["Price increases after 1-year guarantee", "Upload speeds limited on cable plans", "Fiber not available everywhere"],
      "coverage": ["NY","TX","CA","FL","OH","NC","WI","MO","KY","SC","GA","TN","AL","IN","LA","MS","ME","MA","MN","NE","NV","NH","NJ","NM","OR","WA","WV","HI","IL"],
      "phone": "",
      "promo": "$500 contract buyout + WiFi 7 router + FREE Spectrum Mobile on Gig plans",
      "topCities": ["New York, NY","Los Angeles, CA","Chicago, IL","San Antonio, TX","Dallas, TX","San Diego, CA","Austin, TX","Orlando, FL","Atlanta, GA","Indianapolis, IN","Charlotte, NC","Saint Louis, MO","Columbus, OH","Tampa, FL","Milwaukee, WI","Louisville, KY","Cincinnati, OH","Raleigh, NC","Cleveland, OH","Buffalo, NY"],
      "plans": [
        {"name": "Internet Advantage", "speed": 100, "uploadSpeed": 10, "price": 30.00, "promoPrice": 30.00, "contract": "None", "dataCap": "Unlimited", "features": ["Free modem", "No data caps", "No contracts", "1-year price guarantee"]},
        {"name": "Internet Premier", "speed": 500, "uploadSpeed": 20, "price": 50.00, "promoPrice": 50.00, "contract": "None", "dataCap": "Unlimited", "features": ["Free modem", "No data caps", "Great for 4K streaming", "1-year price guarantee"]},
        {"name": "Internet Gig", "speed": 1000, "uploadSpeed": 35, "price": 70.00, "promoPrice": 70.00, "contract": "None", "dataCap": "Unlimited", "features": ["WiFi 7 router included", "Spectrum Mobile (1 yr)", "$500 contract buyout", "No data caps"]},
        {"name": "Internet Gig Fiber", "speed": 1000, "uploadSpeed": 1000, "price": 70.00, "promoPrice": 70.00, "contract": "None", "dataCap": "Unlimited", "type": "fiber", "features": ["Symmetrical 1 Gig", "WiFi 7 router included", "Spectrum Mobile (1 yr)", "$500 contract buyout"]},
        {"name": "Internet 2 Gig", "speed": 2000, "uploadSpeed": 2000, "price": 90.00, "promoPrice": 90.00, "contract": "None", "dataCap": "Unlimited", "type": "fiber", "features": ["2 Gig symmetrical", "WiFi 7 router included", "Spectrum Mobile (1 yr)", "$500 contract buyout"]}
      ]
    },
    {
      "id": "verizon",
      "name": "Verizon",
      "slug": "verizon",
      "logo": "https://cdn.builder.io/api/v1/image/assets%2F3e261a0dd1144caf9d53950dd45223ca%2F6d357edf1c8c4637a7a6b59f415fdb47?format=webp&width=200",
      "types": ["5g"],
      "rating": 4.5,
      "reviewCount": 72340,
      "isPartner": True,
      "description": "Verizon 5G Home Internet delivers nationwide fixed wireless broadband with a 4–5 year written price lock — the longest in the category. Plans start at $50/mo ($35/mo with a qualifying Verizon mobile plan) and include a $200–$300 Prepaid Mastercard for new customers. Self-install in minutes, no data caps, no annual contracts.",
      "pros": ["4–5 year written price lock (longest in fixed wireless)", "$200–$300 Prepaid Mastercard for new customers", "$35/mo with qualifying Verizon mobile plan", "Self-install in minutes — no technician", "Nationwide availability", "No equipment fees", "No data caps on all plans"],
      "cons": ["Speeds vary by 5G/LTE signal at your address", "Upload speeds trail fiber (max ~100 Mbps)"],
      "coverage": ["AL","AK","AZ","AR","CA","CO","CT","DE","FL","GA","HI","ID","IL","IN","IA","KS","KY","LA","ME","MD","MA","MI","MN","MS","MO","MT","NE","NV","NH","NJ","NM","NY","NC","ND","OH","OK","OR","PA","RI","SC","SD","TN","TX","UT","VT","VA","WA","WV","WI","WY","DC"],
      "phone": "",
      "promo": "$200\u2013$300 Prepaid Mastercard + 4\u20135 year price lock + $35/mo with Verizon mobile plan",
      "topCities": ["New York, NY","Los Angeles, CA","Chicago, IL","Houston, TX","Phoenix, AZ","Philadelphia, PA","San Antonio, TX","San Diego, CA","Dallas, TX","San Jose, CA","Austin, TX","Jacksonville, FL","Columbus, OH","Charlotte, NC","Indianapolis, IN","San Francisco, CA","Seattle, WA","Denver, CO","Nashville, TN","Oklahoma City, OK"],
      "plans": [
        {"name": "5G Home", "speed": 300, "uploadSpeed": 50, "price": 50.00, "promoPrice": 50.00, "contract": "None", "dataCap": "Unlimited", "type": "5g", "features": ["4-year price lock", "$35/mo with qualifying mobile plan", "$200\u2013$300 Prepaid Mastercard", "No equipment fees", "Self-setup in minutes"]},
        {"name": "5G Home Plus", "speed": 1000, "uploadSpeed": 100, "price": 70.00, "promoPrice": 70.00, "contract": "None", "dataCap": "Unlimited", "type": "5g", "features": ["4-year price lock", "$45/mo with qualifying mobile plan", "$200\u2013$300 Prepaid Mastercard", "Wi-Fi Cloud storage", "Premium streaming perks"]},
        {"name": "5G Home Ultimate", "speed": 1000, "uploadSpeed": 100, "price": 85.00, "promoPrice": 85.00, "contract": "None", "dataCap": "Unlimited", "type": "5g", "features": ["5-year price lock", "$60/mo with qualifying mobile plan", "$300 Prepaid Mastercard", "Premium hardware included"]}
      ]
    },
    {
      "id": "att",
      "name": "AT&T Fiber",
      "slug": "att-fiber",
      "logo": "https://cdn.builder.io/api/v1/image/assets%2F3e261a0dd1144caf9d53950dd45223ca%2Fef6f3e2465234cdfb2ff3447dd85c201?format=webp&width=200",
      "types": ["fiber"],
      "rating": 4.4,
      "reviewCount": 62150,
      "isPartner": True,
      "description": "AT&T Fiber delivers blazing-fast symmetrical speeds from 300 Mbps to 5 Gbps with no data caps, no equipment fees, and no annual contracts. Every plan includes a $100–$200 Reward Card and the new AT&T All-Fi Pro Wi-Fi 7 gateway on premium tiers. AutoPay/Paperless discounts make it even more affordable.",
      "pros": ["Symmetrical upload/download speeds", "No data caps", "No equipment fees", "$100–$200 Reward Card on every plan", "All-Fi Pro Wi-Fi 7 on 2 Gig+ plans", "ActiveArmor internet security included", "No annual contracts"],
      "cons": ["Fiber not available in all areas", "Professional installation required in most cases"],
      "coverage": ["TX","CA","FL","IL","GA","MI","OH","NC","TN","AL","AR","IN","KS","KY","LA","MO","MS","NV","OK","SC","WI","AZ","PA","CO","MN","WA"],
      "phone": "",
      "promo": "$100–$200 Reward Card + Wi-Fi 7 on premium plans — no equipment fees, no data caps",
      "topCities": ["Houston, TX","Chicago, IL","Los Angeles, CA","Miami, FL","San Antonio, TX","Las Vegas, NV","Phoenix, AZ","Dallas, TX","Austin, TX","Atlanta, GA","Indianapolis, IN","Charlotte, NC","Nashville, TN","Milwaukee, WI","Louisville, KY","Detroit, MI","Columbus, OH","Jacksonville, FL","Denver, CO","Orlando, FL"],
      "plans": [
        {"name": "Internet 300", "speed": 300, "uploadSpeed": 300, "price": 35.00, "promoPrice": 35.00, "contract": "None", "dataCap": "Unlimited", "features": ["$100 Reward Card", "Symmetrical speeds", "No equipment fees", "AutoPay/Paperless discount"]},
        {"name": "Internet 500", "speed": 500, "uploadSpeed": 500, "price": 45.00, "promoPrice": 45.00, "contract": "None", "dataCap": "Unlimited", "features": ["$100 Reward Card", "Great for 4K streaming", "No equipment fees", "AutoPay/Paperless discount"]},
        {"name": "Internet 1000", "speed": 1000, "uploadSpeed": 1000, "price": 60.00, "promoPrice": 60.00, "contract": "None", "dataCap": "Unlimited", "features": ["$100 Reward Card", "1 Gig symmetrical", "No equipment fees", "Best for families"]},
        {"name": "Internet 2000", "speed": 2000, "uploadSpeed": 2000, "price": 110.00, "promoPrice": 110.00, "contract": "None", "dataCap": "Unlimited", "features": ["$200 Reward Card", "All-Fi Pro Wi-Fi 7 included", "ActiveArmor security", "Multi-gig speeds"]},
        {"name": "Internet 5000", "speed": 5000, "uploadSpeed": 5000, "price": 180.00, "promoPrice": 180.00, "contract": "None", "dataCap": "Unlimited", "features": ["$200 Reward Card", "All-Fi Pro Wi-Fi 7 included", "ActiveArmor security", "10 GbE port", "Fastest AT&T plan"]}
      ]
    },
    {
      "id": "frontier",
      "name": "Frontier",
      "slug": "frontier",
      "logo": "https://cdn.builder.io/api/v1/image/assets%2F3e261a0dd1144caf9d53950dd45223ca%2F2b7ba1b758ee4b8a9c57cc4b6a65c54c?format=webp&width=200",
      "types": ["fiber"],
      "rating": 4.1,
      "reviewCount": 24680,
      "isPartner": True,
      "description": "Frontier Fiber delivers 100% fiber-optic internet from 200 Mbps to 7 Gbps — the widest speed tier range of any fiber provider. All plans include a premium WiFi router, no data caps, no overage charges, and discounts for Verizon Mobile bundling and YouTube TV subscribers.",
      "pros": ["Speeds from 200 Mbps to 7 Gbps", "No annual contracts", "No data caps or overage charges", "Premium WiFi router included", "Verizon Mobile bundle discount", "YouTube TV discount", "Auto Pay discount"],
      "cons": ["Fiber not available everywhere", "Limited TV bundle options"],
      "coverage": ["CA","TX","FL","CT","NY","WV","IN","OH","PA","AZ","AL","IL","SC","TN","NM","GA","NC","MN","WI","MS","NE","IA","OR","WA"],
      "phone": "",
      "promo": "Fiber from $30/mo + Verizon Mobile bundle savings + premium WiFi router included",
      "topCities": ["Los Angeles, CA","Tampa, FL","Dallas, TX","Fort Worth, TX","Hartford, CT","New Haven, CT","Rochester, NY","Fort Wayne, IN","Long Beach, CA","Sarasota, FL","St. Petersburg, FL","Clearwater, FL","Lakeland, FL","Durham, NC","Plano, TX","Irving, TX","Frisco, TX","McKinney, TX","Denton, TX","Beaverton, OR"],
      "plans": [
        {"name": "Fiber 200", "speed": 200, "uploadSpeed": 200, "price": 30.00, "promoPrice": 30.00, "contract": "None", "dataCap": "Unlimited", "features": ["Premium WiFi router", "Verizon Mobile bundle discount", "YouTube TV discount", "Auto Pay discount"]},
        {"name": "Fiber 500", "speed": 500, "uploadSpeed": 500, "price": 45.00, "promoPrice": 45.00, "contract": "None", "dataCap": "Unlimited", "features": ["Premium WiFi router", "Verizon Mobile bundle discount", "YouTube TV discount", "Auto Pay discount"]},
        {"name": "Fiber 1 Gig", "speed": 1000, "uploadSpeed": 1000, "price": 65.00, "promoPrice": 65.00, "contract": "None", "dataCap": "Unlimited", "features": ["Premium WiFi router", "Verizon Mobile bundle discount", "YouTube TV discount", "Auto Pay discount"]},
        {"name": "Fiber 2 Gig", "speed": 2000, "uploadSpeed": 2000, "price": 100.00, "promoPrice": 100.00, "contract": "None", "dataCap": "Unlimited", "features": ["Premium WiFi router", "YouTube TV discount", "Auto Pay discount", "Multi-gig speeds"]},
        {"name": "Fiber 5 Gig", "speed": 5000, "uploadSpeed": 5000, "price": 150.00, "promoPrice": 150.00, "contract": "None", "dataCap": "Unlimited", "features": ["Premium mesh WiFi", "YouTube TV discount", "Auto Pay discount", "Ultra-fast fiber"]},
        {"name": "Fiber 7 Gig", "speed": 7000, "uploadSpeed": 7000, "price": 200.00, "promoPrice": 200.00, "contract": "None", "dataCap": "Unlimited", "features": ["Fastest residential plan available", "Premium mesh WiFi", "YouTube TV discount", "Best for power users"]}
      ]
    },
    {
      "id": "att-air",
      "name": "AT&T Air",
      "slug": "att-air",
      "logo": "https://cdn.builder.io/api/v1/image/assets%2F3e261a0dd1144caf9d53950dd45223ca%2Fe91068d6188b48c396f5bea1838f8e4b?format=webp&width=200",
      "types": ["5g"],
      "rating": 4.2,
      "reviewCount": 15300,
      "isPartner": True,
      "description": "AT&T Air is fixed wireless home internet powered by AT&T's 5G and LTE network. Simple self-install, no equipment fees, no data caps, no price increases after 12 months — and just $35/mo when bundled with an AT&T wireless plan.",
      "pros": ["Quick self-install — no technician needed", "No annual contract", "No equipment fees", "No data caps", "No price increases after 12 months", "$35/mo with wireless plan bundle"],
      "cons": ["Speeds vary by location and congestion", "Requires compatible wireless coverage at your address"],
      "coverage": ["Nationwide"],
      "phone": "",
      "promo": "Only $35/mo with wireless plan — no install needed, no equipment fees, no price hikes",
      "topCities": ["Los Angeles, CA","Chicago, IL","Philadelphia, PA","Detroit, MI","Las Vegas, NV","Phoenix, AZ","Houston, TX","Dallas, TX","Atlanta, GA","Miami, FL","San Francisco, CA","Seattle, WA","Denver, CO","Boston, MA","Washington, DC","San Diego, CA","Austin, TX","Indianapolis, IN","Charlotte, NC","Nashville, TN"],
      "plans": [
        {"name": "AT&T Air Internet", "speed": 200, "uploadSpeed": 30, "price": 55.00, "promoPrice": 55.00, "contract": "None", "dataCap": "Unlimited", "features": ["Simple self-install", "No price increases after 12 months", "No equipment fees", "AT&T All-Fi gateway"]},
        {"name": "AT&T Air (with wireless bundle)", "speed": 200, "uploadSpeed": 30, "price": 35.00, "promoPrice": 35.00, "contract": "None", "dataCap": "Unlimited", "features": ["Bundle discount with AT&T wireless plan", "Simple self-install", "No equipment fees", "No data caps"]}
      ]
    },
    {
      "id": "ziply",
      "name": "Ziply Fiber",
      "slug": "ziply",
      "logo": "https://cdn.builder.io/api/v1/image/assets%2F3e261a0dd1144caf9d53950dd45223ca%2Ffc510a11bfda45d5a2fc1c49f8e8e27d?format=webp&width=200",
      "types": ["fiber"],
      "rating": 4.3,
      "reviewCount": 12450,
      "isPartner": False,
      "description": "Ziply Fiber provides some of the cheapest fiber internet in the country, starting at just $20/mo for 100 Mbps symmetrical. With speeds up to 10 Gbps, no contracts, and no data caps, Ziply is a standout option in the Pacific Northwest.",
      "pros": ["Cheapest fiber in the US — from $20/mo", "Symmetrical speeds up to 10 Gbps", "No contracts", "No data caps", "WiFi equipment included", "Excellent uptime"],
      "cons": ["Limited to Pacific Northwest (WA, OR, ID)", "Newer provider in some neighborhoods"],
      "coverage": ["WA","OR","ID"],
      "phone": "",
      "promo": "Fiber from just $20/mo — no contracts, no data caps",
      "topCities": ["Seattle, WA","Portland, OR","Beaverton, OR","Redmond, WA","Everett, WA","Kennewick, WA","Coeur d'Alene, ID","Kirkland, WA","Bellevue, WA","Bothell, WA","Tacoma, WA","Olympia, WA","Vancouver, WA","Hillsboro, OR","Tigard, OR"],
      "plans": [
        {"name": "Fiber 100", "speed": 100, "uploadSpeed": 100, "price": 20.00, "promoPrice": 20.00, "contract": "None", "dataCap": "Unlimited", "features": ["Symmetrical speeds", "No data caps", "WiFi equipment included"]},
        {"name": "Fiber 300", "speed": 300, "uploadSpeed": 300, "price": 35.00, "promoPrice": 35.00, "contract": "None", "dataCap": "Unlimited", "features": ["Symmetrical speeds", "No data caps", "WiFi equipment included"]},
        {"name": "Fiber 1 Gig", "speed": 1000, "uploadSpeed": 1000, "price": 60.00, "promoPrice": 60.00, "contract": "None", "dataCap": "Unlimited", "features": ["1 Gig symmetrical", "No data caps", "WiFi equipment included"]},
        {"name": "Fiber 2 Gig", "speed": 2000, "uploadSpeed": 2000, "price": 90.00, "promoPrice": 90.00, "contract": "None", "dataCap": "Unlimited", "features": ["2 Gig symmetrical", "Multi-gig router included", "No data caps"]},
        {"name": "Fiber 10 Gig", "speed": 10000, "uploadSpeed": 10000, "price": 300.00, "promoPrice": 300.00, "contract": "None", "dataCap": "Unlimited", "features": ["10 Gig symmetrical", "Fastest residential fiber available", "No data caps"]}
      ]
    },
    {
      "id": "tmobile",
      "name": "T-Mobile Fiber",
      "slug": "tmobile-fiber",
      "logo": "https://cdn.builder.io/api/v1/image/assets%2F3e261a0dd1144caf9d53950dd45223ca%2F9051bda6af7849e1b75f0240b3b88182?format=webp&width=200",
      "types": ["fiber"],
      "rating": 4.3,
      "reviewCount": 18200,
      "isPartner": True,
      "description": "T-Mobile Fiber delivers premium fiber-optic internet managed by T-Mobile through local fiber partnerships. All plans include a Wi-Fi 6 router, unlimited data, and a $200 back promotion — with no annual contracts required.",
      "pros": ["Symmetrical fiber speeds", "Wi-Fi 6 router included", "No contracts", "No data caps", "$200 back promo for new customers", "Managed by T-Mobile"],
      "cons": ["Available in select markets only", "Fewer plan options than competitors"],
      "coverage": ["CO","FL","IL","CA"],
      "phone": "",
      "promo": "Get $200 back + Wi-Fi 6 router included — symmetrical fiber from $55/mo",
      "topCities": ["Pueblo, CO","North Port, FL","Rockford, IL","Palmdale, CA","Lancaster, CA","Victorville, CA","Hesperia, CA","Apple Valley, CA","Barstow, CA","Ridgecrest, CA"],
      "plans": [
        {"name": "T-Mobile Fiber 500", "speed": 500, "uploadSpeed": 500, "price": 55.00, "promoPrice": 55.00, "contract": "None", "dataCap": "Unlimited", "features": ["Symmetrical speeds", "Wi-Fi 6 router included", "No data caps", "$200 back promo"]},
        {"name": "T-Mobile Fiber 1 Gig", "speed": 1000, "uploadSpeed": 1000, "price": 100.00, "promoPrice": 100.00, "contract": "None", "dataCap": "Unlimited", "features": ["Symmetrical upload/download", "Wi-Fi 6 router included", "No data caps", "$200 back promo"]}
      ]
    },
    {
      "id": "cox",
      "name": "Cox",
      "slug": "cox",
      "logo": "https://cdn.builder.io/api/v1/image/assets%2F3e261a0dd1144caf9d53950dd45223ca%2F621e5ae7fa8d4b7d915e455df5aad1a6?format=webp&width=200",
      "types": ["cable"],
      "rating": 4.0,
      "reviewCount": 45600,
      "isPartner": False,
      "description": "Cox Communications offers fiber-backed cable internet with multi-year price stability and Panoramic WiFi included on higher tiers. With 5 speed tiers from 100 Mbps to 2 Gbps, Cox provides solid coverage across the Southwest and Southern US.",
      "pros": ["Multi-year price locks (up to 2 years)", "Panoramic WiFi included on 500 Mbps+", "Speeds up to 2 Gbps", "No annual contracts", "Reliable service"],
      "cons": ["1.25 TB data cap on most plans", "Unlimited data costs extra ($50/mo)", "Higher starting prices than some competitors"],
      "coverage": ["AZ","NV","CA","OK","NE","LA","KS","VA","RI","FL","AL","GA"],
      "phone": "",
      "promo": "Panoramic WiFi included (2 yrs) on 500 Mbps+ plans",
      "topCities": ["Phoenix, AZ","Las Vegas, NV","San Diego, CA","Oklahoma City, OK","Omaha, NE","New Orleans, LA","Baton Rouge, LA","Tucson, AZ","Wichita, KS","Virginia Beach, VA","Norfolk, VA","Providence, RI","Pensacola, FL","Scottsdale, AZ","Mesa, AZ","Chandler, AZ","Tulsa, OK","Irvine, CA","Henderson, NV","Mobile, AL"],
      "plans": [
        {"name": "Go Fast", "speed": 100, "uploadSpeed": 10, "price": 50.00, "promoPrice": 50.00, "contract": "None", "dataCap": "1.25 TB", "features": ["1-year price lock", "No annual contract"]},
        {"name": "Go Faster", "speed": 250, "uploadSpeed": 25, "price": 70.00, "promoPrice": 70.00, "contract": "None", "dataCap": "1.25 TB", "features": ["1-year price lock", "No annual contract"]},
        {"name": "Go Even Faster", "speed": 500, "uploadSpeed": 50, "price": 90.00, "promoPrice": 90.00, "contract": "None", "dataCap": "1.25 TB", "features": ["2-year price lock", "Panoramic WiFi included (2 yrs)", "No annual contract"]},
        {"name": "Go Super Fast", "speed": 1000, "uploadSpeed": 100, "price": 110.00, "promoPrice": 110.00, "contract": "None", "dataCap": "1.25 TB", "features": ["2-year price lock", "Panoramic WiFi included (2 yrs)", "No annual contract"]},
        {"name": "Go Beyond Fast", "speed": 2000, "uploadSpeed": 200, "price": 150.00, "promoPrice": 150.00, "contract": "None", "dataCap": "1.25 TB", "features": ["2-year price lock", "Panoramic WiFi included (2 yrs)", "No annual contract"]}
      ]
    },
    {
      "id": "tmobile-5g",
      "name": "T-Mobile 5G Home Internet",
      "slug": "tmobile-5g",
      "logo": "https://cdn.builder.io/api/v1/image/assets%2F3e261a0dd1144caf9d53950dd45223ca%2F2fe221f9cb074ccf97fb3001edfd0dcd?format=webp&width=200",
      "types": ["5g"],
      "rating": 4.1,
      "reviewCount": 28450,
      "isPartner": False,
      "description": "T-Mobile 5G Home Internet leverages the nation's largest 5G network with no contracts, no data caps, no equipment fees, and a price lock guarantee. New customers get a $200–$300 Virtual Prepaid Mastercard plus streaming perks. Bundle with a T-Mobile phone plan for as low as $30/mo.",
      "pros": ["No contracts", "No data caps", "No equipment fees", "Price lock guarantee", "$200–$300 Virtual Prepaid Mastercard", "As low as $30/mo with phone bundle", "15-day test drive"],
      "cons": ["Speed varies by location (133–415 Mbps typical)", "Requires 5G/LTE coverage at your address"],
      "coverage": ["Nationwide"],
      "phone": "",
      "promo": "$200–$300 Prepaid Mastercard + streaming perks — price lock guarantee",
      "topCities": ["New York, NY","Los Angeles, CA","Chicago, IL","Houston, TX","Phoenix, AZ","Philadelphia, PA","San Antonio, TX","San Diego, CA","Dallas, TX","San Jose, CA","Austin, TX","Jacksonville, FL","Indianapolis, IN","Seattle, WA","Denver, CO","Washington, DC","Nashville, TN","Oklahoma City, OK","Portland, OR","Las Vegas, NV"],
      "plans": [
        {"name": "Home Internet", "speed": 245, "uploadSpeed": 31, "price": 50.00, "promoPrice": 50.00, "contract": "None", "dataCap": "Unlimited", "features": ["Price lock guarantee", "Free gateway device", "$200–$300 Prepaid Mastercard", "Streaming perks", "15-day test drive"]},
        {"name": "Home Internet Plus", "speed": 245, "uploadSpeed": 31, "price": 70.00, "promoPrice": 70.00, "contract": "None", "dataCap": "Unlimited", "features": ["Wi-Fi mesh system included", "Unlimited tech support", "Price lock guarantee", "$200–$300 Prepaid Mastercard", "Streaming perks"]},
        {"name": "Home Internet (Bundled)", "speed": 245, "uploadSpeed": 31, "price": 35.00, "promoPrice": 30.00, "contract": "None", "dataCap": "Unlimited", "features": ["With premium T-Mobile phone plan", "Price lock guarantee", "Free gateway", "Streaming perks"]}
      ]
    },
    {
      "id": "windstream",
      "name": "Kinetic by Windstream",
      "slug": "windstream",
      "logo": "https://cdn.builder.io/api/v1/image/assets%2F3e261a0dd1144caf9d53950dd45223ca%2Fe8238f2705844011b827624ae722a3fc?format=webp&width=200",
      "types": ["fiber","dsl"],
      "rating": 3.9,
      "reviewCount": 15680,
      "isPartner": True,
      "description": "Kinetic by Windstream offers fiber internet with speeds up to 2 Gbps, no contracts, and free installation for fiber upgrades. Save $20/mo by bundling with AT&T Wireless. Kinetic specializes in bringing high-speed fiber to rural and suburban communities across 18 states.",
      "pros": ["$20/mo off with AT&T Wireless bundle", "No contracts", "Free installation for fiber upgrades", "Speeds up to 2 Gbps", "No data caps on fiber", "Available in rural areas"],
      "cons": ["Fiber still expanding to new areas", "DSL speeds vary by distance from node"],
      "coverage": ["AR","GA","KY","NE","NM","NY","NC","OH","OK","PA","SC","TX","FL","IA","MN","AL","MS","WV"],
      "phone": "",
      "promo": "Save $20/mo with AT&T Wireless — free installation on fiber upgrades",
      "topCities": ["Lexington, KY","Lincoln, NE","Richmond, TX","Sugar Land, TX","Broken Arrow, OK","Concord, NC","Canton, GA","Dalton, GA","Valdosta, GA","Salisbury, NC","Statesville, NC","Mooresville, NC","Kannapolis, NC","Somerset, KY","Winchester, KY","Norfolk, NE","Kearney, NE","Pflugerville, TX","Bastrop, TX","Manor, TX"],
      "plans": [
        {"name": "Kinetic Fiber 300", "speed": 300, "uploadSpeed": 300, "price": 39.99, "promoPrice": 39.99, "contract": "None", "dataCap": "Unlimited", "type": "fiber", "features": ["$20/mo off with AT&T Wireless", "No contracts", "Free installation for fiber upgrades"]},
        {"name": "Kinetic Fiber 500", "speed": 500, "uploadSpeed": 500, "price": 50.00, "promoPrice": 50.00, "contract": "None", "dataCap": "Unlimited", "type": "fiber", "features": ["$20/mo off with AT&T Wireless", "No contracts", "Work from home ready"]},
        {"name": "Kinetic Fiber 1 Gig", "speed": 1000, "uploadSpeed": 1000, "price": 65.00, "promoPrice": 65.00, "contract": "None", "dataCap": "Unlimited", "type": "fiber", "features": ["$20/mo off with AT&T Wireless", "No contracts", "Free installation for fiber upgrades"]},
        {"name": "Kinetic Fiber 2 Gig", "speed": 2000, "uploadSpeed": 2000, "price": 100.00, "promoPrice": 100.00, "contract": "None", "dataCap": "Unlimited", "type": "fiber", "features": ["$20/mo off with AT&T Wireless", "No contracts", "Free installation for fiber upgrades", "Multi-gig speeds"]}
      ]
    },
    {
      "id": "optimum",
      "name": "Optimum",
      "slug": "optimum",
      "logo": "https://cdn.builder.io/api/v1/image/assets%2F3e261a0dd1144caf9d53950dd45223ca%2F38a2edd4db2944e597f7499c46ec551d?format=webp&width=200",
      "types": ["fiber","cable"],
      "rating": 4.0,
      "reviewCount": 31250,
      "isPartner": True,
      "description": "Optimum delivers fiber internet with an industry-leading 5-year price lock on every plan — no surprises, no annual contracts, no data caps. Plans from $30/mo to 8 Gbps for power users, plus up to $200 in Visa Prepaid Cards for new customers. Free installation on online orders.",
      "pros": ["5-year price lock on all plans", "No annual contracts", "No data caps", "Up to $200 Visa Prepaid Card", "Free installation for online orders", "Speeds up to 8 Gbps"],
      "cons": ["Limited to select regions (Northeast, NV, TX, WV)", "Cable plans being phased out in favor of fiber"],
      "coverage": ["NY","NJ","CT","PA","NV","TX","WV"],
      "phone": "",
      "promo": "5-year price lock + up to $200 Visa Prepaid Card — fiber from just $30/mo",
      "topCities": ["New York, NY","Newark, NJ","Jersey City, NJ","Henderson, NV","Amarillo, TX","Lubbock, TX","Stamford, CT","Bridgeport, CT","Norwalk, CT","Waterbury, CT","Danbury, CT","Milford, CT","Stratford, CT","Fairfield, CT","Greenwich, CT","Westport, CT","Bryan, TX","College Station, TX","Charleston, WV","Parkersburg, WV"],
      "plans": [
        {"name": "Fiber 300", "speed": 300, "uploadSpeed": 300, "price": 30.00, "promoPrice": 30.00, "contract": "None", "dataCap": "Unlimited", "type": "fiber", "features": ["5-year price lock", "Up to $200 Visa Prepaid Card", "Free installation", "No contracts, no data caps"]},
        {"name": "Fiber 500", "speed": 500, "uploadSpeed": 500, "price": 45.00, "promoPrice": 45.00, "contract": "None", "dataCap": "Unlimited", "type": "fiber", "features": ["5-year price lock", "Up to $200 Visa Prepaid Card", "Free installation", "No contracts, no data caps"]},
        {"name": "Fiber 1 Gig", "speed": 1000, "uploadSpeed": 1000, "price": 60.00, "promoPrice": 60.00, "contract": "None", "dataCap": "Unlimited", "type": "fiber", "features": ["5-year price lock", "Up to $200 Visa Prepaid Card", "Free installation", "No contracts, no data caps"]},
        {"name": "Fiber 2 Gig", "speed": 2000, "uploadSpeed": 2000, "price": 80.00, "promoPrice": 80.00, "contract": "None", "dataCap": "Unlimited", "type": "fiber", "features": ["5-year price lock", "Up to $200 Visa Prepaid Card", "Free installation", "No contracts, no data caps"]},
        {"name": "Fiber 5 Gig", "speed": 5000, "uploadSpeed": 5000, "price": 120.00, "promoPrice": 120.00, "contract": "None", "dataCap": "Unlimited", "type": "fiber", "features": ["5-year price lock", "Up to $200 Visa Prepaid Card", "Free installation", "No contracts, no data caps"]},
        {"name": "Fiber 8 Gig", "speed": 8000, "uploadSpeed": 8000, "price": 150.00, "promoPrice": 150.00, "contract": "None", "dataCap": "Unlimited", "type": "fiber", "features": ["5-year price lock", "Up to $200 Visa Prepaid Card", "Free installation", "Fastest Optimum plan"]}
      ]
    },
    {
      "id": "earthlink",
      "name": "EarthLink",
      "slug": "earthlink",
      "logo": "https://cdn.builder.io/api/v1/image/assets%2F3e261a0dd1144caf9d53950dd45223ca%2F3e0270cc21bc43a5afc4d42a4c9a79d9?format=webp&width=200",
      "types": ["fiber","fixed-wireless"],
      "rating": 3.8,
      "reviewCount": 12340,
      "isPartner": True,
      "description": "EarthLink delivers internet nationwide through partnerships with major fiber networks, offering speeds up to 5 Gbps. Enjoy introductory rates as low as $39.95/mo on Fiber 1 Gig, $100–$200 Mastercard Reward Cards, and straightforward pricing with no data caps or speed throttling.",
      "pros": ["No data caps", "No speed throttling", "Nationwide availability", "$100–$200 Mastercard Reward Cards", "Intro rate: Fiber 1 Gig from $39.95/mo", "24/7 customer support", "Wireless Home Internet option"],
      "cons": ["Uses partner networks (availability varies)", "One-time professional installation fee"],
      "coverage": ["Nationwide"],
      "phone": "",
      "promo": "Fiber 1 Gig from $39.95/mo intro + $100–$200 Mastercard Reward — no data caps",
      "topCities": ["Chicago, IL","Los Angeles, CA","Atlanta, GA","Dallas, TX","Houston, TX","Miami, FL","New York, NY","Philadelphia, PA","Phoenix, AZ","San Antonio, TX","San Diego, CA","Austin, TX","Jacksonville, FL","Charlotte, NC","San Francisco, CA","Indianapolis, IN","Seattle, WA","Denver, CO","Washington, DC","Nashville, TN"],
      "plans": [
        {"name": "Fiber 100", "speed": 100, "uploadSpeed": 100, "price": 49.95, "promoPrice": 49.95, "contract": "None", "dataCap": "Unlimited", "type": "fiber", "features": ["No data caps", "24/7 support", "No speed throttling"]},
        {"name": "Fiber 300", "speed": 300, "uploadSpeed": 300, "price": 54.95, "promoPrice": 54.95, "contract": "None", "dataCap": "Unlimited", "type": "fiber", "features": ["Symmetrical speeds", "No data caps", "24/7 support"]},
        {"name": "Fiber 1 Gig", "speed": 1000, "uploadSpeed": 1000, "price": 89.95, "promoPrice": 39.95, "contract": "None", "dataCap": "Unlimited", "type": "fiber", "features": ["$39.95/mo for first 3 months", "$100–$200 Mastercard Reward Card", "No data caps"]},
        {"name": "Fiber 2 Gig", "speed": 2000, "uploadSpeed": 2000, "price": 110.00, "promoPrice": 110.00, "contract": "None", "dataCap": "Unlimited", "type": "fiber", "features": ["$100–$200 Mastercard Reward Card", "Multi-gig speeds", "No data caps"]},
        {"name": "Fiber 5 Gig", "speed": 5000, "uploadSpeed": 5000, "price": 150.00, "promoPrice": 150.00, "contract": "None", "dataCap": "Unlimited", "type": "fiber", "features": ["$100–$200 Mastercard Reward Card", "Fastest EarthLink plan", "No data caps"]},
        {"name": "Wireless Home Internet", "speed": 200, "uploadSpeed": 25, "price": 55.00, "promoPrice": 55.00, "contract": "None", "dataCap": "Unlimited", "type": "fixed-wireless", "features": ["No wiring needed", "Self-install option", "No data caps"]}
      ]
    },
    {
      "id": "brightspeed",
      "name": "Brightspeed",
      "slug": "brightspeed",
      "logo": "https://cdn.builder.io/api/v1/image/assets%2F3e261a0dd1144caf9d53950dd45223ca%2F39cee5de8f0e40889266615565a12003?format=webp&width=200",
      "types": ["fiber","dsl"],
      "rating": 3.7,
      "reviewCount": 8920,
      "isPartner": True,
      "description": "Brightspeed is rapidly deploying next-gen fiber across 20 states, from 200 Mbps to an industry-leading 8 Gbps. Enjoy $100–$200 Prepaid Cards for new customers, free installation on higher tiers, and a 1-year price lock on the 2 Gig plan. Fiber starts at just $30/mo.",
      "pros": ["Fiber from just $30/mo", "Speeds up to 8 Gbps", "$100–$200 Prepaid Cards for new customers", "Free installation on higher tiers", "No data caps", "Aggressive fiber expansion in underserved areas"],
      "cons": ["Fiber still limited in many areas", "DSL speeds on legacy network are slower"],
      "coverage": ["NC","SC","OH","PA","FL","TX","MN","WI","IL","IN","VA","TN","AL","MS","MO","KS","OK","AR","LA","NM"],
      "phone": "",
      "promo": "$100–$200 Prepaid Card + free installation — fiber from just $30/mo",
      "topCities": ["Fayetteville, NC","Wilmington, NC","Greenville, NC","High Point, NC","Gastonia, NC","Concord, NC","Hickory, NC","Burlington, NC","Salisbury, NC","Mooresville, NC","Rocky Mount, NC","Wilson, NC","Goldsboro, NC","Jacksonville, NC","Columbia, MO","Jefferson City, MO","Mansfield, OH","Charlottesville, VA","Statesville, NC","Kannapolis, NC"],
      "plans": [
        {"name": "Fiber 200", "speed": 200, "uploadSpeed": 200, "price": 30.00, "promoPrice": 30.00, "contract": "None", "dataCap": "Unlimited", "type": "fiber", "features": ["$100–$200 Prepaid Card", "Symmetrical speeds", "No data caps"]},
        {"name": "Fiber 500", "speed": 500, "uploadSpeed": 500, "price": 50.00, "promoPrice": 50.00, "contract": "None", "dataCap": "Unlimited", "type": "fiber", "features": ["$100–$200 Prepaid Card", "Symmetrical speeds", "No data caps"]},
        {"name": "Fiber 1 Gig", "speed": 1000, "uploadSpeed": 1000, "price": 65.00, "promoPrice": 65.00, "contract": "None", "dataCap": "Unlimited", "type": "fiber", "features": ["$100–$200 Prepaid Card", "1 Gig symmetrical", "No data caps"]},
        {"name": "Fiber 2 Gig", "speed": 2000, "uploadSpeed": 2000, "price": 70.00, "promoPrice": 70.00, "contract": "None", "dataCap": "Unlimited", "type": "fiber", "features": ["1-year price lock", "$100–$200 Prepaid Card", "Free installation", "No data caps"]},
        {"name": "Fiber 8 Gig", "speed": 8000, "uploadSpeed": 8000, "price": 90.00, "promoPrice": 90.00, "contract": "None", "dataCap": "Unlimited", "type": "fiber", "features": ["$100–$200 Prepaid Card", "Free installation", "Fastest Brightspeed plan", "No data caps"]}
      ]
    },
    {
      "id": "altafiber",
      "name": "altafiber",
      "slug": "altafiber",
      "logo": "https://cdn.builder.io/api/v1/image/assets%2F3e261a0dd1144caf9d53950dd45223ca%2F2ea544de7e044408beece242f703f7d8?format=webp&width=200",
      "types": ["fiber"],
      "rating": 4.3,
      "reviewCount": 18450,
      "isPartner": True,
      "description": "altafiber (formerly Cincinnati Bell) provides true fiber-to-the-home internet in the Greater Cincinnati tri-state area. With symmetrical speeds from 400 Mbps to 2 Gbps, competitive pricing from $40/mo, and locally based customer support, altafiber is a top fiber choice in Ohio, Kentucky, and Indiana.",
      "pros": ["True fiber to the home", "Symmetrical speeds", "No data caps", "Local customer service in Cincinnati area", "Competitive pricing from $40/mo"],
      "cons": ["Limited to Cincinnati tri-state area (OH, KY, IN)", "Smaller service footprint"],
      "coverage": ["OH","KY","IN"],
      "phone": "",
      "promo": "Fiber from $40/mo — local service, symmetrical speeds, no data caps",
      "topCities": ["Cincinnati, OH","Dayton, OH","Covington, KY","Newport, KY","Florence, KY","Independence, KY","Erlanger, KY","Burlington, KY","Alexandria, KY","Fort Thomas, KY","Fort Mitchell, KY","Highland Heights, KY","Cold Spring, KY","Bellevue, KY","Ludlow, KY"],
      "plans": [
        {"name": "Fiber 400", "speed": 400, "uploadSpeed": 400, "price": 40.00, "promoPrice": 40.00, "contract": "None", "dataCap": "Unlimited", "features": ["Symmetrical speeds", "No data caps", "Local support"]},
        {"name": "Fiber 1 Gig", "speed": 1000, "uploadSpeed": 1000, "price": 60.00, "promoPrice": 60.00, "contract": "None", "dataCap": "Unlimited", "features": ["1 Gig symmetrical", "No data caps", "Local support"]},
        {"name": "Fiber 2 Gig", "speed": 2000, "uploadSpeed": 2000, "price": 90.00, "promoPrice": 90.00, "contract": "None", "dataCap": "Unlimited", "features": ["2 Gig symmetrical", "Premium WiFi", "No data caps"]}
      ]
    },
    {
      "id": "xfinity",
      "name": "Xfinity",
      "slug": "xfinity",
      "logo": "https://cdn.builder.io/api/v1/image/assets%2F3e261a0dd1144caf9d53950dd45223ca%2F1b2ae9888a40472786b58a962b7de37e?format=webp&width=200",
      "types": ["cable","fiber"],
      "rating": 3.9,
      "reviewCount": 72000,
      "isPartner": False,
      "description": "Xfinity by Comcast offers one of the widest ranges of internet plans in the industry — from $20/mo budget plans to a 10 Gbps premium fiber service. Their 5-year price guarantees, Peacock Premium streaming (2 yrs), and a free Xfinity Mobile line (1 yr) on Gigabit plans make it a compelling all-in-one value.",
      "pros": ["Plans from $20/mo to 10 Gbps", "5-year price guarantee on most plans", "Peacock Premium included (2 yrs) on 300 Mbps+", "Free Xfinity Mobile line (1 yr) on 300 Mbps+", "Wide nationwide availability", "Self-install available"],
      "cons": ["1.2 TB data cap on most plans", "Price increases after guarantee period", "Equipment rental fee applies"],
      "coverage": ["Nationwide"],
      "phone": "",
      "promo": "5-year price lock + Peacock Premium (2 yrs) + FREE Xfinity Mobile (1 yr)",
      "topCities": ["Houston, TX","Chicago, IL","Miami, FL","Philadelphia, PA","Minneapolis, MN","Denver, CO","Orlando, FL","Atlanta, GA","San Jose, CA","Seattle, WA","Indianapolis, IN","Portland, OR","Jacksonville, FL","San Francisco, CA","Sacramento, CA","Pittsburgh, PA","Washington, DC","Baltimore, MD","Boston, MA","Detroit, MI"],
      "plans": [
        {"name": "Connect", "speed": 150, "uploadSpeed": 10, "price": 20.00, "promoPrice": 20.00, "contract": "None", "dataCap": "1.2 TB", "features": ["Basic internet", "Self-install available"]},
        {"name": "Connect More", "speed": 300, "uploadSpeed": 15, "price": 35.00, "promoPrice": 35.00, "contract": "None", "dataCap": "1.2 TB", "features": ["5-year price guarantee", "Peacock Premium (2 yrs)", "Xfinity Mobile (1 yr)"]},
        {"name": "Fast", "speed": 500, "uploadSpeed": 20, "price": 50.00, "promoPrice": 50.00, "contract": "None", "dataCap": "1.2 TB", "features": ["5-year price guarantee", "Peacock Premium (2 yrs)", "Xfinity Mobile (1 yr)"]},
        {"name": "Superfast", "speed": 800, "uploadSpeed": 25, "price": 60.00, "promoPrice": 60.00, "contract": "None", "dataCap": "1.2 TB", "features": ["5-year price guarantee", "Peacock Premium (2 yrs)", "Xfinity Mobile (1 yr)"]},
        {"name": "Ultrafast", "speed": 1000, "uploadSpeed": 35, "price": 70.00, "promoPrice": 70.00, "contract": "None", "dataCap": "1.2 TB", "features": ["5-year price guarantee", "Peacock Premium (2 yrs)", "Xfinity Mobile (1 yr)"]},
        {"name": "Gigabit Extra", "speed": 1200, "uploadSpeed": 40, "price": 80.00, "promoPrice": 80.00, "contract": "None", "dataCap": "1.2 TB", "features": ["5-year price guarantee", "Peacock Premium (2 yrs)", "Xfinity Mobile (1 yr)"]},
        {"name": "Gigabit x2", "speed": 2000, "uploadSpeed": 200, "price": 100.00, "promoPrice": 100.00, "contract": "None", "dataCap": "Unlimited", "features": ["5-year price guarantee", "Peacock Premium (2 yrs)", "Xfinity Mobile (1 yr)", "Unlimited data"]},
        {"name": "X10 Fiber", "speed": 10000, "uploadSpeed": 10000, "price": 299.95, "promoPrice": 299.95, "contract": "None", "dataCap": "Unlimited", "type": "fiber", "features": ["10 Gbps symmetrical", "Premium fiber service", "Unlimited data"]}
      ]
    },
    {
      "id": "starlink",
      "name": "Starlink",
      "slug": "starlink",
      "logo": "https://cdn.builder.io/api/v1/image/assets%2F3e261a0dd1144caf9d53950dd45223ca%2F387cce831a8d4640a49d0ea939ddaf11?format=webp&width=200",
      "types": ["satellite"],
      "rating": 4.0,
      "reviewCount": 32000,
      "isPartner": False,
      "description": "Starlink by SpaceX provides low-latency satellite internet virtually anywhere — ideal for rural and underserved areas where traditional broadband can't reach. With speeds of 50–250+ Mbps, no contracts, and multiple tiers including Roam and Priority plans, Starlink is the top satellite choice.",
      "pros": ["Available almost anywhere in the US", "Low latency for satellite (20–40ms)", "No contracts", "Self-install kit", "Multiple plan tiers", "Speeds up to 500 Mbps on Priority"],
      "cons": ["Equipment purchase required ($299–$599)", "Speeds vary with network congestion", "Weather can affect signal"],
      "coverage": ["Nationwide"],
      "phone": "",
      "promo": "As low as $90/mo in high-capacity areas — no contracts",
      "topCities": ["Austin, TX","Denver, CO","Seattle, WA","Portland, OR","Boise, ID","Salt Lake City, UT","Reno, NV","Sacramento, CA","Phoenix, AZ","Albuquerque, NM","Houston, TX","Oklahoma City, OK","Kansas City, MO","Des Moines, IA","Minneapolis, MN","Indianapolis, IN","Columbus, OH","Charlotte, NC","Atlanta, GA","Orlando, FL"],
      "plans": [
        {"name": "Starlink Residential", "speed": 150, "uploadSpeed": 15, "price": 120.00, "promoPrice": 120.00, "contract": "None", "dataCap": "Unlimited", "features": ["Low latency", "Self-install", "No contract", "$90/mo in high-capacity areas"]},
        {"name": "Starlink Roam", "speed": 150, "uploadSpeed": 15, "price": 150.00, "promoPrice": 150.00, "contract": "None", "dataCap": "Unlimited", "features": ["Portable service", "Use anywhere", "No contract"]},
        {"name": "Starlink Priority", "speed": 500, "uploadSpeed": 40, "price": 250.00, "promoPrice": 250.00, "contract": "None", "dataCap": "1 TB priority", "features": ["Prioritized network access", "Faster speeds", "Business-ready", "Up to 500 Mbps"]}
      ]
    },
    {
      "id": "viasat",
      "name": "Viasat",
      "slug": "viasat",
      "logo": "https://cdn.builder.io/api/v1/image/assets%2F3e261a0dd1144caf9d53950dd45223ca%2Fbb597591bba645a286380af7dcc2bccc?format=webp&width=200",
      "types": ["satellite"],
      "rating": 3.4,
      "reviewCount": 18500,
      "isPartner": False,
      "description": "Viasat offers satellite internet through their Choice Plans with speeds up to 100–150 Mbps on newer satellites. Available almost anywhere in the US, Viasat is an option for rural areas where wired broadband isn't available. Introductory rates for the first 3 months.",
      "pros": ["Available almost everywhere", "Speeds up to 100–150 Mbps", "Introductory rates for 3 months", "Built-in WiFi modem"],
      "cons": ["Data caps (60–500 GB)", "Higher latency than wired", "Speeds throttled after data cap", "Equipment lease fees apply"],
      "coverage": ["Nationwide"],
      "phone": "",
      "promo": "Introductory rates for first 3 months",
      "topCities": ["Austin, TX","Denver, CO","Seattle, WA","Portland, OR","Boise, ID","Salt Lake City, UT","Reno, NV","Sacramento, CA","Phoenix, AZ","Albuquerque, NM"],
      "plans": [
        {"name": "Choice 50", "speed": 50, "uploadSpeed": 5, "price": 70.00, "promoPrice": 50.00, "contract": "2-year", "dataCap": "60 GB", "features": ["Introductory rate for 3 months", "Built-in WiFi"]},
        {"name": "Choice 100", "speed": 100, "uploadSpeed": 10, "price": 120.00, "promoPrice": 100.00, "contract": "2-year", "dataCap": "200 GB", "features": ["Introductory rate for 3 months", "HD streaming capable"]},
        {"name": "Choice 150", "speed": 150, "uploadSpeed": 10, "price": 175.00, "promoPrice": 150.00, "contract": "2-year", "dataCap": "500 GB", "features": ["Fastest Viasat speeds", "Introductory rate for 3 months", "Best for families"]}
      ]
    },
    {
      "id": "hughesnet",
      "name": "HughesNet",
      "slug": "hughesnet",
      "logo": "https://cdn.builder.io/api/v1/image/assets%2F3e261a0dd1144caf9d53950dd45223ca%2Ff2da6daca5354abd8d41c5b0c349d86d?format=webp&width=200",
      "types": ["satellite"],
      "rating": 3.2,
      "reviewCount": 12500,
      "isPartner": False,
      "description": "HughesNet delivers satellite internet to customers nationwide, including the most remote locations. Their 2026 lineup includes Select, Elite, and Fusion plans, with $25/mo discounts for the first 12 months. The Fusion plan offers lower latency by combining satellite with terrestrial networks.",
      "pros": ["Available everywhere in the US", "No hard data caps", "Built-in WiFi", "$25/mo discount for first 12 months", "Fusion plan: lower latency"],
      "cons": ["Max speed 25 Mbps", "Higher latency (satellite)", "Speeds reduced after data threshold", "2-year contract required"],
      "coverage": ["Nationwide"],
      "phone": "",
      "promo": "$25/mo off for first 12 months",
      "topCities": ["Austin, TX","Denver, CO","Seattle, WA","Portland, OR","Boise, ID","Salt Lake City, UT","Reno, NV","Sacramento, CA","Phoenix, AZ","Albuquerque, NM"],
      "plans": [
        {"name": "Select", "speed": 25, "uploadSpeed": 3, "price": 49.99, "promoPrice": 24.99, "contract": "2-year", "dataCap": "100 GB", "features": ["$25/mo off for 12 months", "Built-in WiFi", "Basic satellite internet"]},
        {"name": "Elite", "speed": 25, "uploadSpeed": 3, "price": 64.99, "promoPrice": 39.99, "contract": "2-year", "dataCap": "200 GB", "features": ["$25/mo off for 12 months", "More data", "Built-in WiFi"]},
        {"name": "Fusion", "speed": 25, "uploadSpeed": 3, "price": 94.99, "promoPrice": 69.99, "contract": "2-year", "dataCap": "200 GB", "features": ["$25/mo off for 12 months", "Lower latency (satellite + terrestrial)", "Best HughesNet experience"]}
      ]
    },
    {
      "id": "wow",
      "name": "WOW!",
      "slug": "wow",
      "logo": "https://cdn.builder.io/api/v1/image/assets%2F3e261a0dd1144caf9d53950dd45223ca%2F6ee67e05c2f649daad2878f88267cbd0?format=webp&width=200",
      "types": ["fiber","cable"],
      "rating": 4.0,
      "reviewCount": 28300,
      "isPartner": False,
      "description": "WOW! (WideOpenWest) delivers fiber and cable internet with no contracts, no data caps, and competitive pricing from $30/mo. Higher-tier plans include Visa Rewards Cards up to $300 and WiFi equipment. With speeds up to 3 Gbps, WOW! offers exceptional value in the Midwest and Southeast.",
      "pros": ["No annual contracts", "No data caps on all plans", "No equipment fees", "Visa Rewards Cards up to $300 on Gig+ plans", "WiFi included on fiber plans", "Affordable pricing from $30/mo"],
      "cons": ["Limited availability (Midwest/Southeast)", "Upload speeds limited on cable tier"],
      "coverage": ["MI","IL","OH","GA","FL","AL","IN","KY","SC","TN","MO","MS","AR"],
      "phone": "",
      "promo": "No contracts + No data caps + Up to $300 Visa Rewards Card",
      "topCities": ["Detroit, MI","Chicago, IL","Cleveland, OH","Columbus, OH","Montgomery, AL","Auburn, AL","Huntsville, AL","Evansville, IN","Knoxville, TN","Charleston, SC","Augusta, GA","Marietta, GA","Alpharetta, GA","Roswell, GA","Sandy Springs, GA","Duluth, GA","Lawrenceville, GA","Cumming, GA","Canton, GA","Woodstock, GA"],
      "plans": [
        {"name": "Fiber 100", "speed": 100, "uploadSpeed": 100, "price": 30.00, "promoPrice": 30.00, "contract": "None", "dataCap": "Unlimited", "type": "fiber", "features": ["No contracts", "No data caps", "Affordable fiber"]},
        {"name": "Fiber 500", "speed": 500, "uploadSpeed": 500, "price": 50.00, "promoPrice": 50.00, "contract": "None", "dataCap": "Unlimited", "type": "fiber", "features": ["No contracts", "No data caps", "Streaming ready"]},
        {"name": "Fiber 1 Gig", "speed": 1000, "uploadSpeed": 1000, "price": 80.00, "promoPrice": 80.00, "contract": "None", "dataCap": "Unlimited", "type": "fiber", "features": ["Visa Rewards Card up to $300", "No contracts", "No data caps"]},
        {"name": "Internet 1.2 Gig", "speed": 1200, "uploadSpeed": 100, "price": 95.00, "promoPrice": 95.00, "contract": "None", "dataCap": "Unlimited", "features": ["Visa Rewards Card up to $300", "No contracts", "No data caps"]},
        {"name": "Fiber 3 Gig", "speed": 3000, "uploadSpeed": 3000, "price": 100.00, "promoPrice": 100.00, "contract": "None", "dataCap": "Unlimited", "type": "fiber", "features": ["Visa Rewards Card up to $300", "WiFi included", "No contracts", "No data caps"]}
      ]
    },
    {
      "id": "fidium",
      "name": "Fidium",
      "slug": "fidium",
      "logo": "https://cdn.builder.io/api/v1/image/assets%2F3e261a0dd1144caf9d53950dd45223ca%2Fdc35f45653b54bccbe6bd04a8fbe4753?format=webp&width=200",
      "types": ["fiber"],
      "rating": 4.4,
      "reviewCount": 16200,
      "isPartner": False,
      "description": "Fidium Fiber delivers high-speed symmetrical internet with no contracts, no data caps, and straightforward pricing from just $30/mo. WiFi equipment is included on all plans. Fidium is expanding rapidly in New Hampshire, Maine, California, and Texas.",
      "pros": ["True fiber to the home", "Symmetrical upload/download", "No data caps", "No annual contracts", "WiFi equipment included", "From just $30/mo for 100 Mbps"],
      "cons": ["Limited to select regions (NH, ME, CA, TX)", "Expanding but still new in many areas"],
      "coverage": ["ME","NH","CA","TX"],
      "phone": "",
      "promo": "Fiber from just $30/mo — no contracts, symmetrical speeds, WiFi included",
      "topCities": ["Manchester, NH","Portland, ME","Sacramento, CA","Roseville, CA","Katy, TX","Conroe, TX","Nashua, NH","Concord, NH","Dover, NH","Rochester, NH","Portsmouth, NH","South Portland, ME","Lewiston, ME","Bangor, ME","Elk Grove, CA"],
      "plans": [
        {"name": "Fidium 100", "speed": 100, "uploadSpeed": 100, "price": 30.00, "promoPrice": 30.00, "contract": "None", "dataCap": "Unlimited", "features": ["Symmetrical fiber speeds", "No data caps", "WiFi equipment included"]},
        {"name": "Fidium 1 Gig", "speed": 1000, "uploadSpeed": 1000, "price": 55.00, "promoPrice": 55.00, "contract": "None", "dataCap": "Unlimited", "features": ["1 Gig symmetrical", "No data caps", "WiFi equipment included"]},
        {"name": "Fidium 2 Gig", "speed": 2000, "uploadSpeed": 2000, "price": 75.00, "promoPrice": 75.00, "contract": "None", "dataCap": "Unlimited", "features": ["2 Gig symmetrical", "No data caps", "WiFi equipment included"]}
      ]
    },
    {
      "id": "google-fiber",
      "name": "Google Fiber",
      "slug": "google-fiber",
      "logo": "https://cdn.builder.io/api/v1/image/assets%2F3e261a0dd1144caf9d53950dd45223ca%2F19560187fac24080b8cd0fe51eac2697?format=webp&width=200",
      "types": ["fiber"],
      "rating": 4.6,
      "reviewCount": 52000,
      "isPartner": False,
      "description": "Google Fiber delivers premium symmetrical fiber internet with flat, transparent pricing — no promo gimmicks, no annual price hikes. All plans include installation, a Wi-Fi 6E router, and mesh extenders at no extra cost. With speeds up to 8 Gbps, Google Fiber sets the standard for fiber quality.",
      "pros": ["Flat pricing — no promo tricks or annual hikes", "Wi-Fi 6E router + mesh extenders included", "Free installation", "No equipment fees", "No data caps", "Industry-best customer service", "Speeds up to 8 Gbps"],
      "cons": ["Limited to specific cities/neighborhoods", "Premium pricing on lower tiers"],
      "coverage": ["AL","AZ","CA","CO","GA","IL","IN","IA","KS","MO","NC","NE","OH","OK","OR","TN","TX","UT","VA","WA"],
      "phone": "",
      "promo": "Flat pricing + Free install + Wi-Fi 6E router & mesh extenders included",
      "topCities": ["Austin, TX","Atlanta, GA","Charlotte, NC","Kansas City, MO","Nashville, TN","Raleigh, NC","Durham, NC","Salt Lake City, UT","San Antonio, TX","Seattle, WA","Des Moines, IA","Omaha, NE","Mesa, AZ","Miami, FL","San Francisco, CA","Oakland, CA","San Diego, CA","Los Angeles, CA","Portland, OR","Denver, CO"],
      "plans": [
        {"name": "1 Gig", "speed": 1000, "uploadSpeed": 1000, "price": 70.00, "promoPrice": 70.00, "contract": "None", "dataCap": "Unlimited", "features": ["Wi-Fi 6E router", "Mesh extenders", "Free installation", "No equipment fees"]},
        {"name": "2 Gig", "speed": 2000, "uploadSpeed": 2000, "price": 100.00, "promoPrice": 100.00, "contract": "None", "dataCap": "Unlimited", "features": ["Wi-Fi 6E router", "Mesh extenders", "Free installation", "No equipment fees"]},
        {"name": "5 Gig", "speed": 5000, "uploadSpeed": 5000, "price": 125.00, "promoPrice": 125.00, "contract": "None", "dataCap": "Unlimited", "features": ["Wi-Fi 6E router", "Mesh extenders", "Free installation", "No equipment fees"]},
        {"name": "8 Gig", "speed": 8000, "uploadSpeed": 8000, "price": 150.00, "promoPrice": 150.00, "contract": "None", "dataCap": "Unlimited", "features": ["Wi-Fi 6E router", "Mesh extenders", "Free installation", "Fastest Google Fiber plan"]}
      ]
    },
    {
      "id": "geolinks",
      "name": "GeoLinks",
      "slug": "geolinks",
      "logo": "https://cdn.builder.io/api/v1/image/assets%2F3e261a0dd1144caf9d53950dd45223ca%2F0977d0a891e548b9b8f6e76c1bdbb4af?format=webp&width=200",
      "types": ["fixed-wireless"],
      "rating": 4.2,
      "reviewCount": 8900,
      "isPartner": False,
      "description": "GeoLinks specializes in fixed wireless internet using their 'ClearFiber' technology, delivering speeds from 10 Mbps to 10 Gbps. Primarily serving businesses and enterprises with custom solutions, GeoLinks provides scalable, reliable connectivity in areas where fiber infrastructure is limited.",
      "pros": ["ClearFiber fixed wireless technology", "Speeds up to 10 Gbps", "Custom business solutions", "No data caps", "Scalable bandwidth"],
      "cons": ["Primarily business/enterprise focused", "Limited residential availability", "Custom pricing (not always transparent)"],
      "coverage": ["CA","TX","NV","UT","AZ","CO","WY","MT"],
      "phone": "",
      "promo": "Free site survey + Custom pricing for your business needs",
      "topCities": ["Ventura, CA","Los Angeles, CA","Santa Barbara, CA","Las Vegas, NV","Phoenix, AZ","Oxnard, CA","Simi Valley, CA","Thousand Oaks, CA","Camarillo, CA","San Luis Obispo, CA"],
      "plans": [
        {"name": "ClearFiber Basic", "speed": 100, "uploadSpeed": 100, "price": 50.00, "promoPrice": 50.00, "contract": "None", "dataCap": "Unlimited", "features": ["Fixed wireless", "No data caps", "Business-grade reliability"]},
        {"name": "ClearFiber 500", "speed": 500, "uploadSpeed": 500, "price": 150.00, "promoPrice": 150.00, "contract": "None", "dataCap": "Unlimited", "features": ["Symmetrical speeds", "Custom SLA available", "Business-grade"]},
        {"name": "ClearFiber Enterprise", "speed": 10000, "uploadSpeed": 10000, "price": 300.00, "promoPrice": 300.00, "contract": "1-year", "dataCap": "Unlimited", "features": ["Up to 10 Gbps", "Custom enterprise solution", "Dedicated support"]}
      ]
    },
    {
      "id": "uscellular",
      "name": "U.S. Cellular",
      "slug": "uscellular",
      "logo": "https://cdn.builder.io/api/v1/image/assets%2F3e261a0dd1144caf9d53950dd45223ca%2F6d26938a588b49089e10ead8d3710bed?format=webp&width=200",
      "types": ["5g"],
      "rating": 4.1,
      "reviewCount": 21300,
      "isPartner": False,
      "description": "U.S. Cellular offers affordable 5G Home Internet with no contracts, no equipment fees, and simple pricing. Get $10/mo off for the first 12 months, and just $30/mo when bundled with an eligible mobile plan. Strong coverage in the Midwest and rural areas.",
      "pros": ["No annual contracts", "No equipment fees", "$10/mo discount for first 12 months", "Only $30/mo with mobile plan bundle", "Strong Midwest/rural coverage"],
      "cons": ["Speeds vary by location", "5G coverage still expanding"],
      "coverage": ["WI","IA","TN","ME","Nationwide"],
      "phone": "",
      "promo": "$10/mo off for 12 months — only $30/mo with mobile bundle",
      "topCities": ["Milwaukee, WI","Madison, WI","Des Moines, IA","Cedar Rapids, IA","Knoxville, TN","Portland, ME","Green Bay, WI","Kenosha, WI","Racine, WI","Appleton, WI","Eau Claire, WI","Janesville, WI","Oshkosh, WI","La Crosse, WI","Sheboygan, WI"],
      "plans": [
        {"name": "5G Home Internet", "speed": 200, "uploadSpeed": 30, "price": 50.00, "promoPrice": 40.00, "contract": "None", "dataCap": "Unlimited", "features": ["$10/mo off for 12 months", "No contracts", "No equipment fees"]},
        {"name": "5G Home Internet (Bundled)", "speed": 200, "uploadSpeed": 30, "price": 30.00, "promoPrice": 30.00, "contract": "None", "dataCap": "Unlimited", "features": ["With eligible mobile plan", "No contracts", "No equipment fees"]}
      ]
    },
    {
      "id": "mediacom",
      "name": "Mediacom",
      "slug": "mediacom",
      "logo": "https://cdn.builder.io/api/v1/image/assets%2F3e261a0dd1144caf9d53950dd45223ca%2F1ed248849bc245399021676bd25b2c29?format=webp&width=200",
      "types": ["cable","fiber"],
      "rating": 3.8,
      "reviewCount": 35600,
      "isPartner": False,
      "description": "Mediacom delivers cable and expanding fiber internet with a growing 2 Gig footprint rolling out in 2026. Their 1 Gig plan comes with a 3-year price lock at $50/mo, and the Xtream Connect program provides internet to qualifying low-income households from $14.99/mo.",
      "pros": ["3-year price lock on 1 Gig plan", "Xtream Connect low-income program ($14.99/mo)", "2 Gig rolling out in 2026", "Flexible plans", "Wide Midwest coverage"],
      "cons": ["Data caps on lower tiers", "Upload speeds limited on cable", "Price varies significantly by tier"],
      "coverage": ["AL","AR","FL","GA","IA","IL","IN","KS","KY","LA","MO","MS","NC","OH","TN","TX","UT","WI"],
      "phone": "",
      "promo": "1 Gig for $50/mo with 3-year price lock — Xtream Connect from $14.99/mo",
      "topCities": ["Des Moines, IA","Cedar Rapids, IA","Davenport, IA","Columbia, MO","Springfield, MO","Gulf Shores, AL","Mobile, AL","Ames, IA","Waterloo, IA","Iowa City, IA","Ankeny, IA","Urbandale, IA","West Des Moines, IA","Council Bluffs, IA","Sioux City, IA"],
      "plans": [
        {"name": "Internet 100", "speed": 100, "uploadSpeed": 10, "price": 49.99, "promoPrice": 49.99, "contract": "None", "dataCap": "600 GB", "features": ["Good for basic use", "Streaming ready"]},
        {"name": "Internet 300", "speed": 300, "uploadSpeed": 30, "price": 30.00, "promoPrice": 30.00, "contract": "None", "dataCap": "1 TB", "features": ["Promotional rate", "Multiple devices", "4K streaming"]},
        {"name": "1 Gig Internet", "speed": 1000, "uploadSpeed": 100, "price": 50.00, "promoPrice": 50.00, "contract": "None", "dataCap": "Unlimited", "features": ["3-year price lock", "Unlimited data", "Gaming optimized"]},
        {"name": "2 Gig Internet", "speed": 2000, "uploadSpeed": 200, "price": 70.00, "promoPrice": 70.00, "contract": "None", "dataCap": "Unlimited", "type": "fiber", "features": ["Rolling out in 2026", "Unlimited data", "Next-gen speeds"]},
        {"name": "Xtream Connect", "speed": 100, "uploadSpeed": 10, "price": 29.99, "promoPrice": 14.99, "contract": "None", "dataCap": "600 GB", "features": ["For qualifying low-income households", "From $14.99/mo", "Digital inclusion program"]}
      ]
    }
  ]
}

outpath = os.path.join(os.path.dirname(__file__), '..', 'src', 'data', 'providers.json')
outpath = os.path.abspath(outpath)
with open(outpath, 'w') as f:
    json.dump(data, f, indent=2)
    f.write('\n')
print(f'Updated providers.json at {outpath} — {len(data["providers"])} providers')
